/**:
  ros__parameters:
    diagnostic_groups:
      overall_diagnostics:
        output_topic_name: /diagnostics/scenario_simulator_v2_adapter/overall_diagnostics
        aggregation_list:
          # - /diagnostics/scenario_simulator_v2_adapter/aeb_diagnostics
          - /diagnostics/scenario_simulator_v2_adapter/planning_validator_diagnostics
          - /diagnostics/scenario_simulator_v2_adapter/collision_detector_diagnostics
          - /diagnostics/scenario_simulator_v2_adapter/control_validator_diagnostics
          - /diagnostics/scenario_simulator_v2_adapter/topic_state_monitor_diagnostics
          # - /diagnostics/scenario_simulator_v2_adapter/path_optimizer_diagnostics
          # - /diagnostics/scenario_simulator_v2_adapter/motion_velocity_planner_diagnostics

      # aeb_diagnostics:
      #   output_topic_name: /diagnostics/scenario_simulator_v2_adapter/aeb_diagnostics
      #   aggregation_list:
      #     # - /diagnostics/autonomous_emergency_braking/aeb_emergency_stop

      planning_validator_diagnostics:
        output_topic_name: /diagnostics/scenario_simulator_v2_adapter/planning_validator_diagnostics
        aggregation_list:
          - /diagnostics/planning_validator/intersection_validation_collision_check
          - /diagnostics/planning_validator/trajectory_validation_acceleration
          - /diagnostics/planning_validator/trajectory_validation_distance_deviation
          - /diagnostics/planning_validator/trajectory_validation_steering
          - /diagnostics/planning_validator/trajectory_validation_steering_rate
          - /diagnostics/planning_validator/trajectory_validation_yaw_deviation
          # - /diagnostics/planning_validator/trajectory_validation_finite
          # - /diagnostics/planning_validator/trajectory_validation_interval
          # - /diagnostics/planning_validator/trajectory_validation_curvature
          # - /diagnostics/planning_validator/trajectory_validation_relative_angle
          # - /diagnostics/planning_validator/rear_collision_check
          # - /diagnostics/planning_validator/trajectory_validation_lateral_acceleration
          # - /diagnostics/planning_validator/trajectory_validation_deceleration
          # - /diagnostics/planning_validator/trajectory_validation_longitudinal_distance_deviation

      collision_detector_diagnostics:
        output_topic_name: /diagnostics/scenario_simulator_v2_adapter/collision_detector_diagnostics
        aggregation_list:
          - /diagnostics/collision_detector/collision_detect

      control_validator_diagnostics:
        output_topic_name: /diagnostics/scenario_simulator_v2_adapter/control_validator_diagnostics
        aggregation_list:
          - /diagnostics/control_validator/control_validation_yaw_deviation
          # - /diagnostics/control_validator/control_validation_rolling_back
          # - /diagnostics/control_validator/control_validation_max_distance_deviation
          # - /diagnostics/control_validator/control_validation_over_velocity
          # - /diagnostics/control_validator/control_validation_overrun_stop_point
          # - /diagnostics/control_validator/control_validation_will_overrun_stop_point

      topic_state_monitor_diagnostics:
        output_topic_name: /diagnostics/scenario_simulator_v2_adapter/topic_state_monitor_diagnostics
        aggregation_list:
          - /diagnostics/topic_state_monitor_mission_planning_route/planning_topic_status
          # - /diagnostics/topic_state_monitor_scenario_planning_trajectory/planning_topic_status
          # - /diagnostics/topic_state_monitor_trajectory_follower_control_cmd/control_topic_status

      # path_optimizer_diagnostics:
      #   output_topic_name: /diagnostics/scenario_simulator_v2_adapter/path_optimizer_diagnostics
      #   aggregation_list:
      #     # - /diagnostics/path_optimizer/path_optimizer_emergency_stop

      # motion_velocity_planner_diagnostics:
      #   output_topic_name: /diagnostics/scenario_simulator_v2_adapter/motion_velocity_planner_diagnostics
      #   aggregation_list:
      #     # - /diagnostics/motion_velocity_planner/boundary_departure
